name: Format, Lint, Unit Test
on: [push]
jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: CI setup
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - name: Install dependencies
      - run: yarn install --frozen-lockfile
      - name: Format check with prettier
      - run: yarn format:check
      - name: Lint check
      - run: yarn lint
      - name: Run unit test
      - run: yarn test
